HEDGE_WORDS = [
    "may",
    "might",
    "could",
    "would",
    "should",
    "believe",
    "think",
    "expect",
    "anticipate",
    "hope",
    "hopefully",
    "assume",
    "suppose",
    "estimate",
    "project",
    "some",
    "somewhat",
    "several",
    "various",
    "a few",
    "a number of",
    "eventually",
    "in due course",
    "going forward",
    "over time",
    "in the coming quarters",
    "in the near term",
    "in the medium term",
    "potentially",
    "possibly",
    "perhaps",
    "maybe",
    "arguably",
    "generally",
    "broadly",
    "roughly",
    "approximately",
    "around",
    "uncertainty",
    "uncertainties",
    "challenges",
    "headwinds",
    "softness",
    "pressure",
    "choppy",
    "volatility",
]

RISK_KEYWORDS = {
    "macro": [
        "inflation",
        "recession",
        "rate hike",
        "interest rates",
        "FX",
        "currency",
        "geopolitical",
        "macro",
    ],
    "supply": [
        "supply chain",
        "shortage",
        "constraint",
        "constraints",
        "disruption",
        "logistics",
        "backlog",
    ],
    "demand": [
        "churn",
        "retention",
        "attrition",
        "slowdown",
        "soft demand",
        "weakness",
        "weakening",
        "deferral",
    ],
    "competitive": [
        "competitive pressure",
        "pricing pressure",
        "share loss",
        "competition",
        "discounting",
    ],
    "operational": [
        "restructure",
        "restructuring",
        "impairment",
        "write-down",
        "writedown",
        "charge",
        "one-time",
        "non-recurring",
        "layoffs",
    ],
    "regulatory": [
        "regulatory",
        "regulation",
        "compliance",
        "investigation",
        "lawsuit",
        "litigation",
        "subpoena",
    ],
    "liquidity": [
        "covenant",
        "refinance",
        "default",
        "liquidity",
        "leverage",
        "debt",
        "amortization",
        "going concern",
    ],
}
